import fs from "node:fs";
import path from "node:path";
import readline from "node:readline";
import * as XLSX from "xlsx";
import { prisma } from "../../config/prisma";
import { MarketDataService, SourceMarketRecord } from "./market-data.service";
import { PrismaAuditService } from "../audit/audit.service";

const file = process.argv[2];
if (!file) throw new Error("Usage: npm run market:import -- <file.csv|xlsx|xls|json>");

function csvColumns(line: string) { const values: string[] = []; let value = ""; let quoted = false; for (let index = 0; index < line.length; index += 1) { const character = line[index]; if (character === '"') { if (quoted && line[index + 1] === '"') { value += '"'; index += 1; } else quoted = !quoted; } else if (character === "," && !quoted) { values.push(value.trim()); value = ""; } else value += character; } values.push(value.trim()); return values; }
function value(row: Record<string, unknown>, ...keys: string[]) { for (const key of keys) if (row[key] !== undefined && row[key] !== null && row[key] !== "") return row[key]; return undefined; }
function sourceRecord(row: Record<string, unknown>): SourceMarketRecord { const arrivals = value(row, "arrivals", "arrival_quantity"); return { source: "historical-file", sourceRecordId: String(value(row, "id", "ID", "record_id") ?? "") || undefined, observedDate: new Date(String(value(row, "arrival_date", "observed_date", "date") ?? "")), commodity: String(value(row, "commodity", "crop") ?? ""), marketId: String(value(row, "market_id", "market_code") ?? "") || undefined, mandiName: String(value(row, "market", "mandi", "market_name") ?? ""), state: String(value(row, "state", "state_name") ?? ""), district: String(value(row, "district", "district_name") ?? ""), minPrice: Number(value(row, "min_price", "minPrice")), maxPrice: Number(value(row, "max_price", "maxPrice")), modalPrice: Number(value(row, "modal_price", "modalPrice")), priceUnit: String(value(row, "price_unit", "unit") ?? "QTL"), arrivals: arrivals === undefined ? null : Number(arrivals) }; }
async function* csvRows(): AsyncGenerator<Record<string, unknown>> { const input = fs.createReadStream(file!, { encoding: "utf8" }); const lines = readline.createInterface({ input, crlfDelay: Infinity }); let headers: string[] | undefined; for await (const line of lines) { if (!line.trim()) continue; const cells = csvColumns(line); if (!headers) { headers = cells.map((header) => header.replace(/^\uFEFF/, "").trim()); continue; } yield Object.fromEntries(headers.map((header, index) => [header, cells[index] ?? ""])); } }
async function* records(): AsyncGenerator<SourceMarketRecord> { const extension = path.extname(file!).toLowerCase(); if (extension === ".csv") { for await (const row of csvRows()) yield sourceRecord(row); return; } if (extension === ".json") { const parsed: unknown = JSON.parse(fs.readFileSync(file!, "utf8")); const rows = Array.isArray(parsed) ? parsed : (parsed && typeof parsed === "object" && Array.isArray((parsed as { records?: unknown[] }).records) ? (parsed as { records: unknown[] }).records : null); if (!rows) throw new Error("JSON import must contain an array or a records array."); for (const row of rows) yield sourceRecord((row && typeof row === "object" ? row : {}) as Record<string, unknown>); return; } if (extension !== ".xlsx" && extension !== ".xls") throw new Error("Supported formats: CSV, XLS, XLSX, and JSON."); const workbook = XLSX.readFile(file!); const sheet = workbook.Sheets[workbook.SheetNames[0]]; for (const row of XLSX.utils.sheet_to_json<Record<string, unknown>>(sheet, { defval: "" })) yield sourceRecord(row); }
async function main() { await prisma.$connect(); const result = await new MarketDataService(prisma).run(records(), "historical-file", "HISTORICAL_IMPORT"); await new PrismaAuditService(prisma).record({ action: "MARKET_DATA_IMPORTED", entityType: "MarketDataImportRun", entityId: result.runId, metadata: { imported: result.imported, rejected: result.rejected } }); console.log(JSON.stringify(result)); await prisma.$disconnect(); }
main().catch(async (error) => { console.error(error); await prisma.$disconnect(); process.exit(1); });
