import { Prisma, PrismaClient, QuantityUnit } from "@prisma/client";
import { MarketDomainError } from "../../common/errors";
import { invalidateMarketCache } from "../market-intelligence/market-cache";

export interface SourceMarketRecord { source: string; sourceRecordId?: string; observedDate: Date; commodity: string; marketId?: string; mandiName: string; state: string; district: string; minPrice: number; maxPrice: number; modalPrice: number; priceUnit: string; arrivals?: number | null; arrivalUnit?: QuantityUnit | null; latitude?: number | null; longitude?: number | null; metadata?: Prisma.InputJsonValue; }
export const normalizeName = (v: string) => v.trim().toLowerCase().replace(/\s+/g, " ");
export function toInrPerQuintal(value: number, unit: string) { const u=normalizeName(unit).replace(/₹|inr/g, "").replace(/\s/g, ""); if (!Number.isFinite(value) || value < 0) throw new MarketDomainError("Invalid price.", "MARKET_DATA_PROVIDER_ERROR"); if (["quintal","qtl","100kg","perquintal"].includes(u)) return value; if (["kg","perkg"].includes(u)) return value*100; throw new MarketDomainError(`Unsupported price unit: ${unit}.`, "UNSUPPORTED_UNIT"); }

export class MarketDataService {
  constructor(private readonly prisma: PrismaClient) {}
  async resolveCrop(source: string, commodity: string) { const normalized=normalizeName(commodity); return this.prisma.crop.findFirst({ where: { OR: [{ name: { equals: commodity, mode:"insensitive" } }, { marketAliases: { some: { source, normalizedAlias: normalized } } }] }, select:{id:true} }); }
  async persist(record: SourceMarketRecord, client: PrismaClient | Prisma.TransactionClient = this.prisma) {
    if (!(record.observedDate instanceof Date) || Number.isNaN(record.observedDate.getTime())) throw new MarketDomainError("Invalid observed date.", "INVALID_DATE");
    if (!record.commodity.trim()) throw new MarketDomainError("Crop name is required.", "UNKNOWN_CROP");
    if (!record.mandiName.trim() || !record.state.trim() || !record.district.trim()) throw new MarketDomainError("Mandi name, state and district are required.", "MARKET_DATA_PROVIDER_ERROR");
    if (![record.minPrice, record.maxPrice, record.modalPrice].every((value) => Number.isFinite(value) && value >= 0)) throw new MarketDomainError("Invalid price value.", "MARKET_DATA_PROVIDER_ERROR");
    if (record.minPrice > record.modalPrice || record.modalPrice > record.maxPrice) throw new MarketDomainError("Minimum, modal and maximum prices are inconsistent.", "MARKET_DATA_PROVIDER_ERROR");
    if (record.arrivals !== undefined && record.arrivals !== null && (!Number.isFinite(record.arrivals) || record.arrivals < 0)) throw new MarketDomainError("Invalid arrivals value.", "MARKET_DATA_PROVIDER_ERROR");
    const hasLatitude = record.latitude !== undefined && record.latitude !== null;
    const hasLongitude = record.longitude !== undefined && record.longitude !== null;
    if (hasLatitude !== hasLongitude || (hasLatitude && (Math.abs(record.latitude as number) > 90 || Math.abs(record.longitude as number) > 180))) throw new MarketDomainError("Invalid market coordinates.", "INVALID_LOCATION");
    const normalized=normalizeName(record.commodity);const crop=await client.crop.findFirst({ where: { OR: [{ name: { equals: record.commodity, mode:"insensitive" } }, { marketAliases: { some: { source:record.source, normalizedAlias: normalized } } }] }, select:{id:true} }); if (!crop) return { imported:false, reason:"UNKNOWN_CROP" as const };
    const normalizedName=normalizeName(record.mandiName); const mandi = record.marketId ? await client.mandi.upsert({ where:{ source_sourceMarketId:{source:record.source,sourceMarketId:record.marketId} }, create:{source:record.source,sourceMarketId:record.marketId,name:record.mandiName,normalizedName,state:record.state,district:record.district,latitude:record.latitude ?? null,longitude:record.longitude ?? null}, update:{name:record.mandiName,state:record.state,district:record.district,latitude:record.latitude ?? undefined,longitude:record.longitude ?? undefined} }) : await client.mandi.upsert({ where:{ source_normalizedName_district_state:{source:record.source,normalizedName,district:record.district,state:record.state} }, create:{source:record.source,name:record.mandiName,normalizedName,state:record.state,district:record.district,latitude:record.latitude ?? null,longitude:record.longitude ?? null}, update:{name:record.mandiName} });
    const [minPrice,maxPrice,modalPrice]=[record.minPrice,record.maxPrice,record.modalPrice].map(v=>toInrPerQuintal(v,record.priceUnit));
    const create={cropId:crop.id,mandiId:mandi.id,source:record.source,sourceRecordId:record.sourceRecordId ?? null,observedDate:record.observedDate,minPrice,maxPrice,modalPrice,arrivalQuantity:record.arrivals ?? null,arrivalUnit:record.arrivalUnit ?? null,sourceMetadata:record.metadata}; const update={minPrice,maxPrice,modalPrice,arrivalQuantity:record.arrivals ?? null,arrivalUnit:record.arrivalUnit ?? null,sourceMetadata:record.metadata,retrievedAt:new Date()};
    if(record.sourceRecordId)await client.mandiPrice.upsert({where:{source_sourceRecordId:{source:record.source,sourceRecordId:record.sourceRecordId}},create,update});else await client.mandiPrice.upsert({where:{cropId_mandiId_observedDate_source:{cropId:crop.id,mandiId:mandi.id,observedDate:record.observedDate,source:record.source}},create,update});
    return { imported:true as const };
  }
  async run(records: AsyncIterable<SourceMarketRecord>, source: string, operation: "HISTORICAL_IMPORT" | "INCREMENTAL_SYNC") { const run=await this.prisma.marketDataImportRun.create({data:{source,operation}}); let read=0, imported=0, rejected=0; let newestObservedDate:Date|undefined; const diagnostics: string[]=[]; const processChunk=async(chunk:SourceMarketRecord[])=>this.prisma.$transaction(async tx=>{for(const record of chunk){try{const outcome=await this.persist(record,tx);if(outcome.imported){imported++;if(!newestObservedDate||record.observedDate>newestObservedDate)newestObservedDate=record.observedDate;}else{rejected++;diagnostics.push(`${record.commodity}: ${outcome.reason}`);}}catch(err){rejected++;diagnostics.push(`${record?.commodity ?? "record"}: ${err instanceof Error?err.message:"Invalid record"}`);}}});try { let chunk:SourceMarketRecord[]=[];for await (const record of records){read++;chunk.push(record);if(chunk.length===250){await processChunk(chunk);chunk=[];}}if(chunk.length)await processChunk(chunk);const status=rejected ? (imported ? "PARTIAL_SUCCESS" : "FAILED") : "SUCCEEDED"; await this.prisma.marketDataImportRun.update({where:{id:run.id},data:{status,recordsRead:read,recordsImported:imported,recordsSkipped:rejected,recordsRejected:rejected,validationFailures:rejected,diagnostics:diagnostics.slice(0,100),completedAt:new Date()}}); if(imported) await invalidateMarketCache(); return {runId:run.id,read,imported,rejected,newestObservedDate}; } catch(err) { await this.prisma.marketDataImportRun.update({where:{id:run.id},data:{status:"FAILED",recordsRead:read,recordsImported:imported,recordsRejected:rejected,validationFailures:rejected,diagnostics:diagnostics.slice(0,100),completedAt:new Date()}}); throw err; } }
}
