import { Prisma, PrismaClient, QuantityUnit } from "@prisma/client";

export interface SourceMarketRecord { source: string; sourceRecordId?: string; observedDate: Date; commodity: string; marketId?: string; mandiName: string; state: string; district: string; minPrice: number; maxPrice: number; modalPrice: number; priceUnit: string; arrivals?: number | null; arrivalUnit?: QuantityUnit | null; latitude?: number | null; longitude?: number | null; metadata?: Prisma.InputJsonValue; }
export const normalizeName = (v: string) => v.trim().toLowerCase().replace(/\s+/g, " ");
export function toInrPerQuintal(value: number, unit: string) { const u=normalizeName(unit).replace(/₹|inr/g, "").replace(/\s/g, ""); if (!Number.isFinite(value) || value < 0) throw new Error("Invalid price"); if (["quintal","qtl","100kg","perquintal"].includes(u)) return value; if (["kg","perkg"].includes(u)) return value*100; throw new Error(`UNSUPPORTED_UNIT:${unit}`); }

export class MarketDataService {
  constructor(private readonly prisma: PrismaClient) {}
  async resolveCrop(source: string, commodity: string) { const normalized=normalizeName(commodity); return this.prisma.crop.findFirst({ where: { OR: [{ name: { equals: commodity, mode:"insensitive" } }, { marketAliases: { some: { source, normalizedAlias: normalized } } }] }, select:{id:true} }); }
  async persist(record: SourceMarketRecord) {
    const crop=await this.resolveCrop(record.source,record.commodity); if (!crop) return { imported:false, reason:"UNKNOWN_CROP" as const };
    const normalizedName=normalizeName(record.mandiName); const mandi = record.marketId ? await this.prisma.mandi.upsert({ where:{ source_sourceMarketId:{source:record.source,sourceMarketId:record.marketId} }, create:{source:record.source,sourceMarketId:record.marketId,name:record.mandiName,normalizedName,state:record.state,district:record.district,latitude:record.latitude ?? null,longitude:record.longitude ?? null}, update:{name:record.mandiName,state:record.state,district:record.district,latitude:record.latitude ?? undefined,longitude:record.longitude ?? undefined} }) : await this.prisma.mandi.upsert({ where:{ source_normalizedName_district_state:{source:record.source,normalizedName,district:record.district,state:record.state} }, create:{source:record.source,name:record.mandiName,normalizedName,state:record.state,district:record.district,latitude:record.latitude ?? null,longitude:record.longitude ?? null}, update:{name:record.mandiName} });
    const [minPrice,maxPrice,modalPrice]=[record.minPrice,record.maxPrice,record.modalPrice].map(v=>toInrPerQuintal(v,record.priceUnit));
    await this.prisma.mandiPrice.upsert({ where:{ cropId_mandiId_observedDate_source:{cropId:crop.id,mandiId:mandi.id,observedDate:record.observedDate,source:record.source} }, create:{cropId:crop.id,mandiId:mandi.id,source:record.source,sourceRecordId:record.sourceRecordId ?? null,observedDate:record.observedDate,minPrice,maxPrice,modalPrice,arrivalQuantity:record.arrivals ?? null,arrivalUnit:record.arrivalUnit ?? null,sourceMetadata:record.metadata}, update:{minPrice,maxPrice,modalPrice,arrivalQuantity:record.arrivals ?? null,arrivalUnit:record.arrivalUnit ?? null,sourceMetadata:record.metadata,retrievedAt:new Date()} });
    return { imported:true as const };
  }
  async run(records: AsyncIterable<SourceMarketRecord>, source: string, operation: "HISTORICAL_IMPORT" | "INCREMENTAL_SYNC") { const run=await this.prisma.marketDataImportRun.create({data:{source,operation}}); let read=0, imported=0, rejected=0; const diagnostics: string[]=[]; try { for await (const record of records) { read++; try { const outcome=await this.persist(record); if(outcome.imported) imported++; else { rejected++; diagnostics.push(`${record.commodity}: ${outcome.reason}`); } } catch(err) { rejected++; diagnostics.push(`${record.commodity}: ${err instanceof Error ? err.message : "Invalid record"}`); } } const status=rejected ? (imported ? "PARTIAL_SUCCESS" : "FAILED") : "SUCCEEDED"; await this.prisma.marketDataImportRun.update({where:{id:run.id},data:{status,recordsRead:read,recordsImported:imported,recordsRejected:rejected,diagnostics:diagnostics.slice(0,100),completedAt:new Date()}}); return {runId:run.id,read,imported,rejected}; } catch(err) { await this.prisma.marketDataImportRun.update({where:{id:run.id},data:{status:"FAILED",recordsRead:read,recordsImported:imported,recordsRejected:rejected,completedAt:new Date()}}); throw err; } }
}
