"use client";
import * as React from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Warehouse as WarehouseIcon, Save } from "lucide-react";
import { RoleProtectedPage } from "@/components/RoleProtectedPage";
import { PageHeader } from "@/components/ui/stat-card";
import { Card, Alert } from "@/components/ui/primitives";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { warehouseApi } from "@/services/warehouseApi";

function Content(){const [warehouseId,setWarehouseId]=React.useState(""); const [unitId,setUnitId]=React.useState(""); const [available,setAvailable]=React.useState(""); const detail=useQuery({queryKey:["warehouse","operator",warehouseId],queryFn:()=>warehouseApi.detail(warehouseId),enabled:!!warehouseId,retry:false}); const save=useMutation({mutationFn:()=>warehouseApi.updateCapacity(warehouseId,unitId,{availableCapacity:Number(available)}),onSuccess:()=>detail.refetch()}); return <div><PageHeader title="Storage Operations" description="Update factual storage-unit capacity and conditions. Recommendations remain driven by the warehouse intelligence engine."/><Card className="mb-6"><div className="grid gap-3 sm:grid-cols-3"><Input value={warehouseId} onChange={e=>setWarehouseId(e.target.value)} placeholder="Warehouse public ID"/><Input value={unitId} onChange={e=>setUnitId(e.target.value)} placeholder="Storage unit public ID"/><Input type="number" min="0" value={available} onChange={e=>setAvailable(e.target.value)} placeholder="Available capacity"/></div><Button className="mt-3 w-auto" disabled={!warehouseId||!unitId||!available} isLoading={save.isPending} onClick={()=>save.mutate()}><Save className="h-4 w-4"/> Update capacity</Button>{save.isError&&<Alert variant="error" className="mt-3">Capacity update failed. Verify the IDs and your warehouse authorization.</Alert>}</Card><Card><div className="mb-3 flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-accent/20"><WarehouseIcon className="h-5 w-5"/></span><div><h2 className="font-semibold">Warehouse detail</h2><p className="text-sm text-muted-foreground">Enter a warehouse public ID to inspect its current state.</p></div></div>{detail.isLoading?<p className="text-sm text-muted-foreground">Loading…</p>:detail.isError?<p className="text-sm text-muted-foreground">No warehouse could be loaded for that ID.</p>:<pre className="max-h-[520px] overflow-auto rounded-2xl bg-[#242424] p-5 text-xs leading-5 text-[#f8f4e9]">{JSON.stringify(detail.data,null,2)}</pre>}</Card></div>}
export default function WarehousePage(){return <RoleProtectedPage role="WAREHOUSE_OPERATOR"><Content/></RoleProtectedPage>}
