-- Module 7: additive buyer matching and negotiation data. No existing rows are altered.
CREATE TYPE "BuyerBusinessType" AS ENUM ('PROCESSOR','WHOLESALER','RETAILER','EXPORTER','INSTITUTIONAL_BUYER','TRADER','OTHER');
CREATE TYPE "BuyerVerificationStatus" AS ENUM ('PENDING','VERIFIED','REJECTED','SUSPENDED');
CREATE TYPE "BuyerDemandStatus" AS ENUM ('DRAFT','ACTIVE','PAUSED','FULFILLED','EXPIRED','CANCELLED');
CREATE TYPE "TradeOfferStatus" AS ENUM ('DRAFT','SENT','COUNTERED','ACCEPTED','REJECTED','WITHDRAWN','EXPIRED','CANCELLED');
CREATE TABLE "buyer_profiles" ("id" TEXT NOT NULL,"publicId" TEXT NOT NULL,"userId" TEXT NOT NULL,"organizationName" TEXT NOT NULL,"businessType" "BuyerBusinessType" NOT NULL,"description" TEXT,"contactPerson" TEXT NOT NULL,"phone" TEXT NOT NULL,"email" TEXT,"address" TEXT,"state" TEXT NOT NULL,"district" TEXT NOT NULL,"latitude" DOUBLE PRECISION,"longitude" DOUBLE PRECISION,"website" TEXT,"verificationStatus" "BuyerVerificationStatus" NOT NULL DEFAULT 'PENDING',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "buyer_profiles_pkey" PRIMARY KEY("id"));
CREATE UNIQUE INDEX "buyer_profiles_publicId_key" ON "buyer_profiles"("publicId"); CREATE UNIQUE INDEX "buyer_profiles_userId_key" ON "buyer_profiles"("userId"); CREATE INDEX "buyer_profiles_verificationStatus_idx" ON "buyer_profiles"("verificationStatus"); CREATE INDEX "buyer_profiles_state_district_idx" ON "buyer_profiles"("state","district"); ALTER TABLE "buyer_profiles" ADD CONSTRAINT "buyer_profiles_userId_fkey" FOREIGN KEY("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "buyer_demands" ("id" TEXT NOT NULL,"publicId" TEXT NOT NULL,"buyerId" TEXT NOT NULL,"cropId" TEXT NOT NULL,"title" TEXT NOT NULL,"description" TEXT,"requiredQuantity" DECIMAL(14,2) NOT NULL,"minimumQuantity" DECIMAL(14,2),"quantityUnit" "QuantityUnit" NOT NULL,"targetPrice" DECIMAL(14,2),"minimumPrice" DECIMAL(14,2),"maximumPrice" DECIMAL(14,2),"qualityRequirements" JSONB,"grade" "QualityGrade","state" TEXT NOT NULL,"district" TEXT NOT NULL,"latitude" DOUBLE PRECISION,"longitude" DOUBLE PRECISION,"deliveryLocation" TEXT,"deliveryStartDate" TIMESTAMP(3),"deliveryEndDate" TIMESTAMP(3),"status" "BuyerDemandStatus" NOT NULL DEFAULT 'DRAFT',"committedQuantity" DECIMAL(14,2) NOT NULL DEFAULT 0,"expiresAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "buyer_demands_pkey" PRIMARY KEY("id"));
CREATE UNIQUE INDEX "buyer_demands_publicId_key" ON "buyer_demands"("publicId"); CREATE INDEX "buyer_demands_buyerId_status_idx" ON "buyer_demands"("buyerId","status"); CREATE INDEX "buyer_demands_cropId_status_idx" ON "buyer_demands"("cropId","status"); CREATE INDEX "buyer_demands_status_expiresAt_idx" ON "buyer_demands"("status","expiresAt"); ALTER TABLE "buyer_demands" ADD CONSTRAINT "buyer_demands_buyerId_fkey" FOREIGN KEY("buyerId") REFERENCES "buyer_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "buyer_demands" ADD CONSTRAINT "buyer_demands_cropId_fkey" FOREIGN KEY("cropId") REFERENCES "crops"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE TABLE "trade_offers" ("id" TEXT NOT NULL,"publicId" TEXT NOT NULL,"lotId" TEXT NOT NULL,"buyerDemandId" TEXT,"buyerId" TEXT NOT NULL,"sellerId" TEXT NOT NULL,"initiatorId" TEXT NOT NULL,"quantity" DECIMAL(14,2) NOT NULL,"quantityUnit" "QuantityUnit" NOT NULL,"offeredPrice" DECIMAL(14,2) NOT NULL,"priceUnit" TEXT NOT NULL DEFAULT 'INR_PER_QUINTAL',"totalValue" DECIMAL(16,2) NOT NULL,"deliveryTerms" TEXT,"message" TEXT,"status" "TradeOfferStatus" NOT NULL DEFAULT 'DRAFT',"expiresAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "trade_offers_pkey" PRIMARY KEY("id"));
CREATE UNIQUE INDEX "trade_offers_publicId_key" ON "trade_offers"("publicId"); CREATE INDEX "trade_offers_lotId_status_idx" ON "trade_offers"("lotId","status"); CREATE INDEX "trade_offers_buyerId_status_idx" ON "trade_offers"("buyerId","status"); CREATE INDEX "trade_offers_buyerDemandId_status_idx" ON "trade_offers"("buyerDemandId","status"); ALTER TABLE "trade_offers" ADD CONSTRAINT "trade_offers_lotId_fkey" FOREIGN KEY("lotId") REFERENCES "crop_lots"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "trade_offers" ADD CONSTRAINT "trade_offers_buyerDemandId_fkey" FOREIGN KEY("buyerDemandId") REFERENCES "buyer_demands"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "trade_offers" ADD CONSTRAINT "trade_offers_buyerId_fkey" FOREIGN KEY("buyerId") REFERENCES "buyer_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE TABLE "trade_offer_revisions" ("id" TEXT NOT NULL,"offerId" TEXT NOT NULL,"revisionNumber" INTEGER NOT NULL,"initiatedBy" TEXT NOT NULL,"quantity" DECIMAL(14,2) NOT NULL,"offeredPrice" DECIMAL(14,2) NOT NULL,"priceUnit" TEXT NOT NULL DEFAULT 'INR_PER_QUINTAL',"deliveryTerms" TEXT,"message" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "trade_offer_revisions_pkey" PRIMARY KEY("id")); CREATE UNIQUE INDEX "trade_offer_revisions_offerId_revisionNumber_key" ON "trade_offer_revisions"("offerId","revisionNumber"); CREATE INDEX "trade_offer_revisions_offerId_createdAt_idx" ON "trade_offer_revisions"("offerId","createdAt"); ALTER TABLE "trade_offer_revisions" ADD CONSTRAINT "trade_offer_revisions_offerId_fkey" FOREIGN KEY("offerId") REFERENCES "trade_offers"("id") ON DELETE CASCADE ON UPDATE CASCADE;
