import { PrismaClient, QuantityUnit, TradeOfferStatus } from "@prisma/client";
import { ConflictError, MarketDomainError, NotFoundError } from "../../common/errors";
import { AuthenticatedUserContext } from "../auth/auth.types";
import { AuditService } from "../audit/audit.service";
import { FarmerProfileResolver } from "../farmers/farmer-profile.resolver";
import { CropLotRepository } from "../lots/lots.repository";
import { LotAuthorizationService } from "../lots/lot.authorization";
import { convertQuantityToKg } from "../fpo/unit-conversion";
import { demandTransitions, offerTransitions, requireTransition } from "./buyer-matching.types";
import { scoreMatch } from "./matching";

const toNum=(x:unknown)=>Number(x); const domain=(m:string,c:any,s=422)=>new MarketDomainError(m,c,s);
export class BuyerMatchingService {
  constructor(private readonly prisma:PrismaClient,private readonly lots:CropLotRepository,private readonly lotAuth:LotAuthorizationService,private readonly farmers:FarmerProfileResolver,private readonly audit:AuditService){}
  private async buyer(userId:string){const p=await this.prisma.buyerProfile.findUnique({where:{userId}});if(!p)throw domain("Buyer profile not found.","BUYER_PROFILE_NOT_FOUND",404);return p;}
  async createProfile(user:AuthenticatedUserContext,input:any){if(user.role!=="BUYER")throw domain("Only buyers can manage buyer profiles.","BUYER_PROFILE_NOT_FOUND",403);if(await this.prisma.buyerProfile.findUnique({where:{userId:user.id}}))throw domain("Buyer profile already exists.","BUYER_PROFILE_ALREADY_EXISTS",409);const p=await this.prisma.buyerProfile.create({data:{...input,userId:user.id,verificationStatus:"PENDING"}});await this.audit.record({actorUserId:user.id,action:"BUYER_PROFILE_CREATED",entityType:"BuyerProfile",entityId:p.id,metadata:{}});return this.publicBuyer(p);}
  async me(user:AuthenticatedUserContext){return this.publicBuyer(await this.buyer(user.id));}
  async updateProfile(user:AuthenticatedUserContext,input:any){const p=await this.buyer(user.id);return this.publicBuyer(await this.prisma.buyerProfile.update({where:{id:p.id},data:input}));}
  publicBuyer(p:any){return {publicId:p.publicId,organizationName:p.organizationName,businessType:p.businessType,description:p.description,state:p.state,district:p.district,verificationStatus:p.verificationStatus,website:p.website};}
  async verify(admin:AuthenticatedUserContext,id:string,status:"VERIFIED"|"REJECTED"|"SUSPENDED"){if(admin.role!=="ADMIN")throw domain("Administrator access is required.","BUYER_PROFILE_NOT_FOUND",403);const p=await this.prisma.buyerProfile.findUnique({where:{id}});if(!p)throw domain("Buyer profile not found.","BUYER_PROFILE_NOT_FOUND",404);const updated=await this.prisma.buyerProfile.update({where:{id},data:{verificationStatus:status}});await this.audit.record({actorUserId:admin.id,action:`BUYER_${status}`,entityType:"BuyerProfile",entityId:id,metadata:{}});return this.publicBuyer(updated);}
  async verifyPublic(admin:AuthenticatedUserContext,publicId:string,status:"VERIFIED"|"REJECTED"|"SUSPENDED"){const p=await this.prisma.buyerProfile.findUnique({where:{publicId}});if(!p)throw domain("Buyer profile not found.","BUYER_PROFILE_NOT_FOUND",404);return this.verify(admin,p.id,status);}
  async createDemand(user:AuthenticatedUserContext,input:any){const b=await this.buyer(user.id);const crop=await this.prisma.crop.findUnique({where:{id:input.cropId}});if(!crop)throw domain("Crop not found.","CROP_NOT_FOUND",404);const d=await this.prisma.buyerDemand.create({data:{...input,buyerId:b.id,qualityRequirements:input.qualityRequirements ?? undefined,grade:input.grade ?? input.qualityRequirements?.grade ?? null}});await this.audit.record({actorUserId:user.id,action:"BUYER_DEMAND_CREATED",entityType:"BuyerDemand",entityId:d.id,metadata:{}});return d;}
  async demands(user:AuthenticatedUserContext){const b=await this.buyer(user.id);return this.prisma.buyerDemand.findMany({where:{buyerId:b.id},orderBy:{createdAt:"desc"}});}
  async demand(user:AuthenticatedUserContext,publicId:string){const d=await this.prisma.buyerDemand.findUnique({where:{publicId}});if(!d)throw domain("Demand not found.","DEMAND_NOT_FOUND",404);const b=await this.buyer(user.id);if(user.role!=="ADMIN"&&d.buyerId!==b.id)throw domain("Demand not found.","DEMAND_NOT_FOUND",404);return d;}
  async transitionDemand(user:AuthenticatedUserContext,publicId:string,to:string){const d=await this.demand(user,publicId);requireTransition(demandTransitions,d.status,to,"INVALID_DEMAND_TRANSITION");const updated=await this.prisma.buyerDemand.update({where:{id:d.id},data:{status:to as any}});await this.audit.record({actorUserId:user.id,action:`BUYER_DEMAND_${to}`,entityType:"BuyerDemand",entityId:d.id,metadata:{}});return updated;}
  async matches(user:AuthenticatedUserContext,lotPublicId:string){const lot=await this.lots.findByPublicId(lotPublicId);if(!lot)throw domain("Lot not found.","LOT_NOT_FOUND",404);const farmer=user.role==="FARMER"?(await this.farmers.ensure(user.id)).id:null;if(!await this.lotAuth.canAccessLot(user,lot,farmer))throw domain("Lot not found.","LOT_NOT_FOUND",404);if(lot.status!=="AVAILABLE"&&lot.status!=="PARTIALLY_COMMITTED")throw domain("Lot is not available.","LOT_NOT_AVAILABLE");const demands=await this.prisma.buyerDemand.findMany({where:{cropId:lot.cropId,status:"ACTIVE",expiresAt:{not:{lt:new Date()}}},take:100,include:{buyer:true}});return {matches:demands.map(d=>{const x=scoreMatch({quantityKg:toNum(lot.availableQuantityKg),minimumQuantityKg:d.minimumQuantity?convertQuantityToKg(toNum(d.minimumQuantity),d.quantityUnit):null,requiredQuantityKg:convertQuantityToKg(toNum(d.requiredQuantity),d.quantityUnit),grade:d.grade,lotLat:lot.farm?.latitude,lotLon:lot.farm?.longitude,demandLat:d.latitude,demandLon:d.longitude,targetPrice:d.targetPrice?toNum(d.targetPrice):null,verification:d.buyer.verificationStatus});return {buyer:this.publicBuyer(d.buyer),demand:{publicId:d.publicId,title:d.title,requiredQuantity:toNum(d.requiredQuantity),quantityUnit:d.quantityUnit,state:d.state,district:d.district},...x};})};}
  private async offerForUser(user:AuthenticatedUserContext,publicId:string){const o=await this.prisma.tradeOffer.findUnique({where:{publicId},include:{buyer:true,demand:true,lot:true,revisions:{orderBy:{revisionNumber:"desc"}}}});if(!o)throw domain("Offer not found.","OFFER_NOT_FOUND",404);const ownsBuyer=user.role==="BUYER"&&o.buyer.userId===user.id;const farmer=user.role==="FARMER"?(await this.farmers.ensure(user.id)).id:null;const ownsLot=await this.lotAuth.canAccessLot(user,o.lot,farmer);if(user.role!=="ADMIN"&&!ownsBuyer&&!ownsLot)throw domain("Offer is not available.","OFFER_NOT_PARTICIPANT",403);if(o.expiresAt&&o.expiresAt<new Date()&&["SENT","COUNTERED"].includes(o.status)){await this.prisma.tradeOffer.update({where:{id:o.id},data:{status:"EXPIRED"}});o.status="EXPIRED";}return o;}
  async createOffer(user:AuthenticatedUserContext,input:any){const lot=await this.lots.findByPublicId(input.lotPublicId);if(!lot)throw domain("Lot not found.","LOT_NOT_FOUND",404);const farmer=user.role==="FARMER"?(await this.farmers.ensure(user.id)).id:null;const ownsLot=await this.lotAuth.canAccessLot(user,lot,farmer);let demand:any=null,buyer:any=null;if(input.buyerDemandPublicId){demand=await this.prisma.buyerDemand.findUnique({where:{publicId:input.buyerDemandPublicId},include:{buyer:true}});if(!demand)throw domain("Demand not found.","DEMAND_NOT_FOUND",404);buyer=demand.buyer;if(user.role!=="BUYER"&&!ownsLot)throw domain("Offer is not available.","OFFER_NOT_PARTICIPANT",403);if(user.role==="BUYER"&&buyer.userId!==user.id)throw domain("Offer is not available.","OFFER_NOT_PARTICIPANT",403);}else {if(!ownsLot)throw domain("Offer is not available.","OFFER_NOT_PARTICIPANT",403);throw domain("A buyer demand is required for an offer.","DEMAND_NOT_ACTIVE");}if(demand.status!=="ACTIVE")throw domain("Demand is not active.","DEMAND_NOT_ACTIVE");if(input.quantityUnit!==demand.quantityUnit)throw domain("Offer quantity unit must match demand.","INVALID_QUANTITY");const kg=convertQuantityToKg(input.quantity,input.quantityUnit);if(kg>toNum(lot.availableQuantityKg))throw domain("Lot does not have sufficient available quantity.","INSUFFICIENT_AVAILABLE_QUANTITY");const o=await this.prisma.tradeOffer.create({data:{lotId:lot.id,buyerDemandId:demand.id,buyerId:buyer.id,sellerId:lot.farmerId??lot.fpoId??"",initiatorId:user.id,quantity:input.quantity,quantityUnit:input.quantityUnit,offeredPrice:input.offeredPrice,totalValue:input.quantity*input.offeredPrice,deliveryTerms:input.deliveryTerms,message:input.message,expiresAt:input.expiresAt,status:"SENT",revisions:{create:{revisionNumber:1,initiatedBy:user.id,quantity:input.quantity,offeredPrice:input.offeredPrice,deliveryTerms:input.deliveryTerms,message:input.message}}}});await this.audit.record({actorUserId:user.id,action:"TRADE_OFFER_SENT",entityType:"TradeOffer",entityId:o.id,metadata:{}});return o;}
  async counter(user:AuthenticatedUserContext,publicId:string,input:any){const o=await this.offerForUser(user,publicId);requireTransition(offerTransitions,o.status,"COUNTERED","INVALID_OFFER_TRANSITION");if(input.quantityUnit!==o.quantityUnit)throw domain("Counter offer unit must match original offer.","INVALID_QUANTITY");const rev=(o.revisions[0]?.revisionNumber??0)+1;const updated=await this.prisma.tradeOffer.update({where:{id:o.id},data:{status:"COUNTERED",quantity:input.quantity,offeredPrice:input.offeredPrice,totalValue:input.quantity*input.offeredPrice,deliveryTerms:input.deliveryTerms,message:input.message,expiresAt:input.expiresAt,revisions:{create:{revisionNumber:rev,initiatedBy:user.id,quantity:input.quantity,offeredPrice:input.offeredPrice,deliveryTerms:input.deliveryTerms,message:input.message}}},include:{revisions:true}});await this.audit.record({actorUserId:user.id,action:"TRADE_OFFER_COUNTERED",entityType:"TradeOffer",entityId:o.id,metadata:{revision:rev}});return updated;}
  async accept(user:AuthenticatedUserContext,publicId:string){const o=await this.offerForUser(user,publicId);requireTransition(offerTransitions,o.status,"ACCEPTED","INVALID_OFFER_TRANSITION");const kg=convertQuantityToKg(toNum(o.quantity),o.quantityUnit);return this.prisma.$transaction(async tx=>{const lot=await tx.cropLot.updateMany({where:{id:o.lotId,availableQuantityKg:{gte:kg}},data:{availableQuantityKg:{decrement:kg}}});if(!lot.count)throw domain("Lot does not have sufficient available quantity.","INSUFFICIENT_AVAILABLE_QUANTITY");if(o.buyerDemandId){const d=await tx.buyerDemand.findUnique({where:{id:o.buyerDemandId}});if(!d||d.status!=="ACTIVE")throw domain("Demand is not active.","DEMAND_NOT_ACTIVE");if(toNum(d.requiredQuantity)-toNum(d.committedQuantity)<toNum(o.quantity))throw domain("Demand quantity is already fulfilled.","DEMAND_QUANTITY_ALREADY_FULFILLED");const committed=toNum(d.committedQuantity)+toNum(o.quantity);await tx.buyerDemand.update({where:{id:d.id},data:{committedQuantity:{increment:o.quantity},status:committed>=toNum(d.requiredQuantity)?"FULFILLED":"ACTIVE"}});}const offer=await tx.tradeOffer.update({where:{id:o.id},data:{status:"ACCEPTED"}});await this.audit.record({actorUserId:user.id,action:"TRADE_OFFER_ACCEPTED",entityType:"TradeOffer",entityId:o.id,metadata:{quantity:toNum(o.quantity)}});return offer;});}
  async offerAction(user:AuthenticatedUserContext,publicId:string,to:"REJECTED"|"WITHDRAWN"){const o=await this.offerForUser(user,publicId);requireTransition(offerTransitions,o.status,to,"INVALID_OFFER_TRANSITION");const updated=await this.prisma.tradeOffer.update({where:{id:o.id},data:{status:to}});await this.audit.record({actorUserId:user.id,action:`TRADE_OFFER_${to}`,entityType:"TradeOffer",entityId:o.id,metadata:{}});return updated;}
  async offers(user:AuthenticatedUserContext){if(user.role==="BUYER"){const b=await this.buyer(user.id);return this.prisma.tradeOffer.findMany({where:{buyerId:b.id},include:{buyer:true,demand:true,lot:{include:{crop:true}}},orderBy:{createdAt:"desc"}});}return [];} async offer(user:AuthenticatedUserContext,id:string){return this.offerForUser(user,id);} async history(user:AuthenticatedUserContext,id:string){const o=await this.offerForUser(user,id);return this.prisma.tradeOfferRevision.findMany({where:{offerId:o.id},orderBy:{revisionNumber:"asc"}});}
}
