import { Prisma, PrismaClient } from "@prisma/client";
import { MarketDomainError, NotFoundError } from "../../common/errors";
import { trackEvent } from "../../config/posthog";
import { AuthenticatedUserContext } from "../auth/auth.types";
import { AuditService } from "../audit/audit.service";
import { FarmerProfileResolver } from "../farmers/farmer-profile.resolver";
import { CropLotRepository } from "../lots/lots.repository";
import { LotAuthorizationService } from "../lots/lot.authorization";
import { convertQuantityToKg } from "../fpo/unit-conversion";
import { demandTransitions, offerTransitions, requireTransition } from "./buyer-matching.types";
import { scoreMatch } from "./matching";
import { getLotMatchesCache, invalidateBuyerMatchingCache, setLotMatchesCache } from "./buyer-matching-cache";

const toNum=(x:unknown)=>Number(x); const domain=(m:string,c:any,s=422)=>new MarketDomainError(m,c,s);
export class BuyerMatchingService {
  constructor(private readonly prisma:PrismaClient,private readonly lots:CropLotRepository,private readonly lotAuth:LotAuthorizationService,private readonly farmers:FarmerProfileResolver,private readonly audit:AuditService){}
  private async buyer(userId:string){const p=await this.prisma.buyerProfile.findUnique({where:{userId}});if(!p)throw domain("Buyer profile not found.","BUYER_PROFILE_NOT_FOUND",404);return p;}
  private validateDemandUpdate(current:any,input:any){const next={...current,...input};if(next.minimumQuantity!==null&&next.minimumQuantity!==undefined&&new Prisma.Decimal(next.minimumQuantity).greaterThan(next.requiredQuantity))throw domain("minimumQuantity cannot exceed requiredQuantity.","INVALID_QUANTITY");if(next.minimumPrice!==null&&next.minimumPrice!==undefined&&next.maximumPrice!==null&&next.maximumPrice!==undefined&&new Prisma.Decimal(next.minimumPrice).greaterThan(next.maximumPrice))throw domain("minimumPrice cannot exceed maximumPrice.","INVALID_PRICE");if((next.latitude===null)!==(next.longitude===null))throw domain("latitude and longitude must be together.","INVALID_LOCATION");if(next.deliveryStartDate&&next.deliveryEndDate&&next.deliveryStartDate>next.deliveryEndDate)throw domain("deliveryStartDate must precede deliveryEndDate.","INVALID_DATE_RANGE");if(next.expiresAt&&next.expiresAt<=new Date())throw domain("Demand expiry must be in the future.","INVALID_DATE");}
  private publicOffer(offer:any){return {publicId:offer.publicId,status:offer.status,quantity:toNum(offer.quantity),quantityUnit:offer.quantityUnit,offeredPrice:toNum(offer.offeredPrice),totalValue:toNum(offer.totalValue),deliveryTerms:offer.deliveryTerms,message:offer.message,expiresAt:offer.expiresAt,createdAt:offer.createdAt,updatedAt:offer.updatedAt,buyer:offer.buyer?this.publicBuyer(offer.buyer):undefined,demand:offer.demand?{publicId:offer.demand.publicId,title:offer.demand.title,status:offer.demand.status}:undefined,lot:offer.lot?{publicId:offer.lot.publicId,crop:offer.lot.crop?{id:offer.lot.crop.id,name:offer.lot.crop.name}:undefined}:undefined};}
  async createProfile(user:AuthenticatedUserContext,input:any){if(user.role!=="BUYER")throw domain("Only buyers can manage buyer profiles.","BUYER_PROFILE_NOT_FOUND",403);if(await this.prisma.buyerProfile.findUnique({where:{userId:user.id}}))throw domain("Buyer profile already exists.","BUYER_PROFILE_ALREADY_EXISTS",409);const p=await this.prisma.buyerProfile.create({data:{...input,userId:user.id,verificationStatus:"PENDING"}});await this.audit.record({actorUserId:user.id,action:"BUYER_PROFILE_CREATED",entityType:"BuyerProfile",entityId:p.id,metadata:{}});trackEvent("buyer_profile_created",user.id,{});return this.publicBuyer(p);}
  async me(user:AuthenticatedUserContext){return this.publicBuyer(await this.buyer(user.id));}
  async updateProfile(user:AuthenticatedUserContext,input:any){const p=await this.buyer(user.id);return this.publicBuyer(await this.prisma.buyerProfile.update({where:{id:p.id},data:input}));}
  publicBuyer(p:any){return {publicId:p.publicId,organizationName:p.organizationName,businessType:p.businessType,description:p.description,state:p.state,district:p.district,verificationStatus:p.verificationStatus,website:p.website};}
  async verify(admin:AuthenticatedUserContext,id:string,status:"VERIFIED"|"REJECTED"|"SUSPENDED"){if(admin.role!=="ADMIN")throw domain("Administrator access is required.","BUYER_PROFILE_NOT_FOUND",403);const p=await this.prisma.buyerProfile.findUnique({where:{id}});if(!p)throw domain("Buyer profile not found.","BUYER_PROFILE_NOT_FOUND",404);const updated=await this.prisma.buyerProfile.update({where:{id},data:{verificationStatus:status}});const action={VERIFIED:"BUYER_VERIFIED",REJECTED:"BUYER_REJECTED",SUSPENDED:"BUYER_SUSPENDED"} as const;await this.audit.record({actorUserId:admin.id,action:action[status],entityType:"BuyerProfile",entityId:id,metadata:{}});await invalidateBuyerMatchingCache();if(status==="VERIFIED")trackEvent("buyer_verified",admin.id,{});return this.publicBuyer(updated);}
  async verifyPublic(admin:AuthenticatedUserContext,publicId:string,status:"VERIFIED"|"REJECTED"|"SUSPENDED"){const p=await this.prisma.buyerProfile.findUnique({where:{publicId}});if(!p)throw domain("Buyer profile not found.","BUYER_PROFILE_NOT_FOUND",404);return this.verify(admin,p.id,status);}
  async createDemand(user:AuthenticatedUserContext,input:any){const b=await this.buyer(user.id);const crop=await this.prisma.crop.findUnique({where:{id:input.cropId}});if(!crop)throw domain("Crop not found.","CROP_NOT_FOUND",404);const d=await this.prisma.buyerDemand.create({data:{...input,buyerId:b.id,qualityRequirements:input.qualityRequirements ?? undefined,grade:input.grade ?? input.qualityRequirements?.grade ?? null}});await this.audit.record({actorUserId:user.id,action:"BUYER_DEMAND_CREATED",entityType:"BuyerDemand",entityId:d.id,metadata:{}});await invalidateBuyerMatchingCache();trackEvent("buyer_demand_created",user.id,{});return d;}
  async demands(user:AuthenticatedUserContext){const b=await this.buyer(user.id);return this.prisma.buyerDemand.findMany({where:{buyerId:b.id},orderBy:{createdAt:"desc"}});}
  async demand(user:AuthenticatedUserContext,publicId:string){const d=await this.prisma.buyerDemand.findUnique({where:{publicId}});if(!d)throw domain("Demand not found.","DEMAND_NOT_FOUND",404);if(user.role!=="ADMIN"){const b=await this.buyer(user.id);if(d.buyerId!==b.id)throw domain("Demand not found.","DEMAND_NOT_FOUND",404);}return d;}
  async updateDemand(user:AuthenticatedUserContext,publicId:string,input:any){const demand=await this.demand(user,publicId);if(demand.status!=="DRAFT"&&demand.status!=="PAUSED")throw domain("Only draft or paused demands can be edited.","INVALID_DEMAND_TRANSITION");this.validateDemandUpdate(demand,input);const { cropId, requiredQuantity, minimumQuantity, quantityUnit, targetPrice, minimumPrice, maximumPrice, qualityRequirements, grade, title, description, state, district, latitude, longitude, deliveryLocation, deliveryStartDate, deliveryEndDate, expiresAt }=input; if(cropId){const crop=await this.prisma.crop.findUnique({where:{id:cropId}});if(!crop)throw domain("Crop not found.","CROP_NOT_FOUND",404);}const updated=await this.prisma.buyerDemand.update({where:{id:demand.id},data:{cropId,requiredQuantity,minimumQuantity,quantityUnit,targetPrice,minimumPrice,maximumPrice,qualityRequirements,grade,title,description,state,district,latitude,longitude,deliveryLocation,deliveryStartDate,deliveryEndDate,expiresAt}});await invalidateBuyerMatchingCache();return updated;}
  async transitionDemand(user:AuthenticatedUserContext,publicId:string,to:"ACTIVE"|"PAUSED"|"CANCELLED"){const d=await this.demand(user,publicId);requireTransition(demandTransitions,d.status,to,"INVALID_DEMAND_TRANSITION");const updated=await this.prisma.buyerDemand.update({where:{id:d.id},data:{status:to}});const action={ACTIVE:"BUYER_DEMAND_ACTIVATED",PAUSED:"BUYER_DEMAND_PAUSED",CANCELLED:"BUYER_DEMAND_CANCELLED"} as const;await this.audit.record({actorUserId:user.id,action:action[to],entityType:"BuyerDemand",entityId:d.id,metadata:{}});await invalidateBuyerMatchingCache();if(to==="ACTIVE")trackEvent("buyer_demand_activated",user.id,{});if(to==="PAUSED")trackEvent("buyer_demand_paused",user.id,{});return updated;}
  async matches(user:AuthenticatedUserContext,lotPublicId:string){const lot=await this.lots.findByPublicId(lotPublicId);if(!lot)throw domain("Lot not found.","LOT_NOT_FOUND",404);const farmer=user.role==="FARMER"?(await this.farmers.ensure(user.id)).id:null;if(!await this.lotAuth.canModifyLot(user,lot,farmer))throw domain("Lot not found.","LOT_NOT_FOUND",404);if(lot.status!=="AVAILABLE"&&lot.status!=="PARTIALLY_COMMITTED")throw domain("Lot is not available.","LOT_NOT_AVAILABLE");const cached=await getLotMatchesCache<unknown>(lotPublicId);if(cached)return cached;const [quality,demands]=await Promise.all([this.prisma.qualityAssessment.findFirst({where:{lotId:lot.id,status:{in:["AI_COMPLETED","VERIFIED"]}},orderBy:{createdAt:"desc"},select:{overallGrade:true}}),this.prisma.buyerDemand.findMany({where:{cropId:lot.cropId,status:"ACTIVE",OR:[{expiresAt:null},{expiresAt:{gte:new Date()}}],buyer:{verificationStatus:"VERIFIED"}},take:100,include:{buyer:true}})]);const lotLatitude=lot.farm?.latitude??lot.fpo?.latitude,lotLongitude=lot.farm?.longitude??lot.fpo?.longitude;const result={matches:demands.map(d=>{const x=scoreMatch({quantityKg:toNum(lot.availableQuantityKg),minimumQuantityKg:d.minimumQuantity?convertQuantityToKg(toNum(d.minimumQuantity),d.quantityUnit):null,requiredQuantityKg:convertQuantityToKg(toNum(d.requiredQuantity),d.quantityUnit),lotGrade:quality?.overallGrade,grade:d.grade,lotLat:lotLatitude,lotLon:lotLongitude,demandLat:d.latitude,demandLon:d.longitude,targetPrice:d.targetPrice?toNum(d.targetPrice):null,verification:d.buyer.verificationStatus});return {buyer:this.publicBuyer(d.buyer),demand:{publicId:d.publicId,title:d.title,requiredQuantity:toNum(d.requiredQuantity),quantityUnit:d.quantityUnit,state:d.state,district:d.district},...x};})};await setLotMatchesCache(lotPublicId,result);trackEvent("lot_matches_viewed",user.id,{});return result;}
  private async offerForUser(user:AuthenticatedUserContext,publicId:string){const o=await this.prisma.tradeOffer.findUnique({where:{publicId},include:{buyer:true,demand:true,lot:{include:{crop:true,farm:true,fpo:true}},revisions:{orderBy:{revisionNumber:"desc"}}}});if(!o)throw domain("Offer not found.","OFFER_NOT_FOUND",404);const ownsBuyer=user.role==="BUYER"&&o.buyer.userId===user.id;const farmer=user.role==="FARMER"?(await this.farmers.ensure(user.id)).id:null;const ownsLot=await this.lotAuth.canModifyLot(user,o.lot,farmer);if(user.role!=="ADMIN"&&!ownsBuyer&&!ownsLot)throw domain("Offer is not available.","OFFER_NOT_PARTICIPANT",403);if(o.expiresAt&&o.expiresAt<new Date()&&["SENT","COUNTERED"].includes(o.status)){await this.prisma.tradeOffer.update({where:{id:o.id},data:{status:"EXPIRED"}});o.status="EXPIRED";}return o;}
  async createOffer(user:AuthenticatedUserContext,input:any){const lot=await this.lots.findByPublicId(input.lotPublicId);if(!lot)throw domain("Lot not found.","LOT_NOT_FOUND",404);const farmer=user.role==="FARMER"?(await this.farmers.ensure(user.id)).id:null;const ownsLot=await this.lotAuth.canModifyLot(user,lot,farmer);let demand:any=null,buyer:any=null;if(input.buyerDemandPublicId){demand=await this.prisma.buyerDemand.findUnique({where:{publicId:input.buyerDemandPublicId},include:{buyer:true}});if(!demand)throw domain("Demand not found.","DEMAND_NOT_FOUND",404);buyer=demand.buyer;if(user.role!=="BUYER"&&!ownsLot)throw domain("Offer is not available.","OFFER_NOT_PARTICIPANT",403);if(user.role==="BUYER"&&buyer.userId!==user.id)throw domain("Offer is not available.","OFFER_NOT_PARTICIPANT",403);}else {if(!ownsLot)throw domain("Offer is not available.","OFFER_NOT_PARTICIPANT",403);throw domain("A buyer demand is required for an offer.","DEMAND_NOT_ACTIVE");}if(demand.status!=="ACTIVE"||buyer.verificationStatus!=="VERIFIED")throw domain("Demand is not active.","DEMAND_NOT_ACTIVE");if(input.quantityUnit!==demand.quantityUnit)throw domain("Offer quantity unit must match demand.","INVALID_QUANTITY");const kg=convertQuantityToKg(input.quantity,input.quantityUnit);if(kg>toNum(lot.availableQuantityKg))throw domain("Lot does not have sufficient available quantity.","INSUFFICIENT_AVAILABLE_QUANTITY");const totalValue=new Prisma.Decimal(input.quantity).mul(input.offeredPrice);const o=await this.prisma.tradeOffer.create({data:{lotId:lot.id,buyerDemandId:demand.id,buyerId:buyer.id,sellerId:lot.farmerId??lot.fpoId??"",initiatorId:user.id,quantity:input.quantity,quantityUnit:input.quantityUnit,offeredPrice:input.offeredPrice,totalValue,deliveryTerms:input.deliveryTerms,message:input.message,expiresAt:input.expiresAt,status:"SENT",revisions:{create:{revisionNumber:1,initiatedBy:user.id,quantity:input.quantity,offeredPrice:input.offeredPrice,deliveryTerms:input.deliveryTerms,message:input.message}}}});await this.audit.record({actorUserId:user.id,action:"TRADE_OFFER_SENT",entityType:"TradeOffer",entityId:o.id,metadata:{}});trackEvent("trade_offer_sent",user.id,{});return this.publicOffer(o);}
  async counter(user:AuthenticatedUserContext,publicId:string,input:any){const o=await this.offerForUser(user,publicId);requireTransition(offerTransitions,o.status,"COUNTERED","INVALID_OFFER_TRANSITION");if(input.quantityUnit!==o.quantityUnit)throw domain("Counter offer unit must match original offer.","INVALID_QUANTITY");const rev=(o.revisions[0]?.revisionNumber??0)+1;const updated=await this.prisma.tradeOffer.update({where:{id:o.id},data:{status:"COUNTERED",quantity:input.quantity,offeredPrice:input.offeredPrice,totalValue:new Prisma.Decimal(input.quantity).mul(input.offeredPrice),deliveryTerms:input.deliveryTerms,message:input.message,expiresAt:input.expiresAt,revisions:{create:{revisionNumber:rev,initiatedBy:user.id,quantity:input.quantity,offeredPrice:input.offeredPrice,deliveryTerms:input.deliveryTerms,message:input.message}}},include:{revisions:true}});await this.audit.record({actorUserId:user.id,action:"TRADE_OFFER_COUNTERED",entityType:"TradeOffer",entityId:o.id,metadata:{revision:rev}});trackEvent("trade_offer_countered",user.id,{});return updated;}
  async accept(user:AuthenticatedUserContext,publicId:string){const o=await this.offerForUser(user,publicId);requireTransition(offerTransitions,o.status,"ACCEPTED","INVALID_OFFER_TRANSITION");if(user.role!=="ADMIN"&&o.initiatorId===user.id)throw domain("Only the other offer participant can accept this offer.","OFFER_NOT_PARTICIPANT",403);const kg=convertQuantityToKg(toNum(o.quantity),o.quantityUnit);const accepted=await this.prisma.$transaction(async tx=>{
    // Each mutation is conditional in the database. A concurrent acceptance
    // that has already consumed lot/demand capacity makes its own transaction
    // fail and roll back rather than overcommitting either side.
    const now=new Date(); const claim=await tx.tradeOffer.updateMany({where:{id:o.id,status:{in:["SENT","COUNTERED"]},OR:[{expiresAt:null},{expiresAt:{gte:now}}]},data:{status:"ACCEPTED"}});if(!claim.count){if(o.expiresAt&&o.expiresAt<now)throw domain("Offer has expired.","OFFER_EXPIRED");throw domain("Offer can no longer be accepted.","INVALID_OFFER_TRANSITION");}
    const lot=await tx.cropLot.updateMany({where:{id:o.lotId,availableQuantityKg:{gte:kg}},data:{availableQuantityKg:{decrement:kg}}});if(!lot.count)throw domain("Lot does not have sufficient available quantity.","INSUFFICIENT_AVAILABLE_QUANTITY");
    if(o.buyerDemandId){const d=await tx.buyerDemand.findUnique({where:{id:o.buyerDemandId}});if(!d||d.status!=="ACTIVE")throw domain("Demand is not active.","DEMAND_NOT_ACTIVE");const remaining=new Prisma.Decimal(d.requiredQuantity).minus(d.committedQuantity).minus(o.quantity);if(remaining.isNegative())throw domain("Demand quantity is already fulfilled.","DEMAND_QUANTITY_ALREADY_FULFILLED");const demand=await tx.buyerDemand.updateMany({where:{id:d.id,status:"ACTIVE",committedQuantity:{lte:new Prisma.Decimal(d.requiredQuantity).minus(o.quantity)}},data:{committedQuantity:{increment:o.quantity},status:remaining.isZero()?"FULFILLED":"ACTIVE"}});if(!demand.count)throw domain("Demand quantity is already fulfilled.","DEMAND_QUANTITY_ALREADY_FULFILLED");}
    return tx.tradeOffer.findUniqueOrThrow({where:{id:o.id}});
  });await this.audit.record({actorUserId:user.id,action:"TRADE_OFFER_ACCEPTED",entityType:"TradeOffer",entityId:o.id,metadata:{quantity:toNum(o.quantity)}});await this.audit.record({actorUserId:user.id,action:"TRADE_OFFER_QUANTITY_COMMITTED",entityType:"CropLot",entityId:o.lotId,metadata:{quantity:toNum(o.quantity)}});await invalidateBuyerMatchingCache();trackEvent("trade_offer_accepted",user.id,{});return this.publicOffer(accepted);}
  async offerAction(user:AuthenticatedUserContext,publicId:string,to:"REJECTED"|"WITHDRAWN"){const o=await this.offerForUser(user,publicId);requireTransition(offerTransitions,o.status,to,"INVALID_OFFER_TRANSITION");if(to==="WITHDRAWN"&&user.role!=="ADMIN"&&o.initiatorId!==user.id)throw domain("Only the offer initiator can withdraw it.","OFFER_NOT_PARTICIPANT",403);const updated=await this.prisma.tradeOffer.update({where:{id:o.id},data:{status:to}});const action={REJECTED:"TRADE_OFFER_REJECTED",WITHDRAWN:"TRADE_OFFER_WITHDRAWN"} as const;await this.audit.record({actorUserId:user.id,action:action[to],entityType:"TradeOffer",entityId:o.id,metadata:{}});if(to==="REJECTED")trackEvent("trade_offer_rejected",user.id,{});return this.publicOffer(updated);}
  async offers(user:AuthenticatedUserContext){const include={buyer:true,demand:true,lot:{include:{crop:true}}};let offers:any[]=[];if(user.role==="BUYER"){const b=await this.buyer(user.id);offers=await this.prisma.tradeOffer.findMany({where:{buyerId:b.id},include,orderBy:{createdAt:"desc"}});}else if(user.role==="FARMER"){const farmer=await this.farmers.ensure(user.id);offers=await this.prisma.tradeOffer.findMany({where:{lot:{farmerId:farmer.id}},include,orderBy:{createdAt:"desc"}});}else if(user.role==="FPO_ADMIN"){const managed=await this.prisma.fpoAdmin.findMany({where:{userId:user.id,status:"ACTIVE"},select:{fpoId:true}});if(managed.length)offers=await this.prisma.tradeOffer.findMany({where:{lot:{fpoId:{in:managed.map(x=>x.fpoId)}}},include,orderBy:{createdAt:"desc"}});}else if(user.role==="ADMIN")offers=await this.prisma.tradeOffer.findMany({include,orderBy:{createdAt:"desc"},take:200});return offers.map(offer=>this.publicOffer(offer));}
  async buyerByPublicId(publicId:string){const p=await this.prisma.buyerProfile.findUnique({where:{publicId}});if(!p)throw domain("Buyer profile not found.","BUYER_PROFILE_NOT_FOUND",404);return this.publicBuyer(p);} async offer(user:AuthenticatedUserContext,id:string){return this.publicOffer(await this.offerForUser(user,id));} async history(user:AuthenticatedUserContext,id:string){const o=await this.offerForUser(user,id);return this.prisma.tradeOfferRevision.findMany({where:{offerId:o.id},orderBy:{revisionNumber:"asc"}});}
}
