import { DataFreshness, MARKET_CONFIG, RecommendationConfidence, TrendDirection, VolatilityLevel } from "./market-intelligence.types";

export const round = (v: number, places = 2) => Math.round(v * 10 ** places) / 10 ** places;
export function average(values: number[]) { return values.length ? values.reduce((a, b) => a + b, 0) / values.length : null; }
export function median(values: number[]) { if (!values.length) return null; const x = [...values].sort((a, b) => a - b); const m = Math.floor(x.length / 2); return x.length % 2 ? x[m] : (x[m - 1] + x[m]) / 2; }
export function percentChange(current: number | null, previous: number | null) { return current === null || previous === null || previous === 0 ? null : round(((current - previous) / previous) * 100); }
export function trend(change: number | null): TrendDirection { if (change === null) return "STABLE"; if (change > MARKET_CONFIG.trendStrong) return "STRONGLY_UP"; if (change >= MARKET_CONFIG.trend) return "UP"; if (change < -MARKET_CONFIG.trendStrong) return "STRONGLY_DOWN"; if (change <= -MARKET_CONFIG.trend) return "DOWN"; return "STABLE"; }
export function volatility(values: number[]): { score: number | null; level: VolatilityLevel } { const mean = average(values); if (!mean || values.length < 3) return { score: null, level: "UNAVAILABLE" }; const sd = Math.sqrt(values.reduce((sum, x) => sum + (x - mean) ** 2, 0) / values.length); const score = round(sd / mean, 4); return { score, level: score >= MARKET_CONFIG.volatilityHigh ? "HIGH" : score >= MARKET_CONFIG.volatilityMedium ? "MEDIUM" : "LOW" }; }
export function freshness(date: Date): DataFreshness { const hours = (Date.now() - date.getTime()) / 3_600_000; if (hours < MARKET_CONFIG.freshHours) return "FRESH"; if (hours < MARKET_CONFIG.recentHours) return "RECENT"; if (hours < MARKET_CONFIG.staleHours) return "STALE"; return "OUTDATED"; }
export function confidence(records: number, dataFreshness: DataFreshness, volatilityScore: number | null): RecommendationConfidence { if (records < 3 || dataFreshness === "OUTDATED") return "INSUFFICIENT_DATA"; if (records >= 14 && dataFreshness === "FRESH" && (volatilityScore === null || volatilityScore < .2)) return "HIGH"; return records >= 7 && dataFreshness !== "STALE" ? "MEDIUM" : "LOW"; }
export function haversineKm(lat1: number, lon1: number, lat2: number, lon2: number) { const r = Math.PI / 180; const a = Math.sin((lat2-lat1)*r/2)**2 + Math.cos(lat1*r)*Math.cos(lat2*r)*Math.sin((lon2-lon1)*r/2)**2; return round(6371 * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a))); }
