import { MarketDomainError, NotFoundError } from "../../common/errors";
import { trackEvent } from "../../config/posthog";
import { AuthenticatedUserContext } from "../auth/auth.types";
import { AuditService } from "../audit/audit.service";
import { CropLotRepository } from "../lots/lots.repository";
import { LotAuthorizationService } from "../lots/lot.authorization";
import { FarmerProfileResolver } from "../farmers/farmer-profile.resolver";
import { average, confidence, freshness, haversineKm, median, percentChange, round, trend, volatility } from "./analytics";
import { MarketIntelligenceRepository } from "./market-intelligence.repository";
import { MARKET_CONFIG, MarketCandidate } from "./market-intelligence.types";

const startOfDay = (d: Date) => new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()));
const daysAgo = (days: number) => { const d = startOfDay(new Date()); d.setUTCDate(d.getUTCDate() - days); return d; };

export class MarketIntelligenceService {
  constructor(private readonly repo: MarketIntelligenceRepository, private readonly lots: CropLotRepository, private readonly lotAuth: LotAuthorizationService, private readonly farmers: FarmerProfileResolver, private readonly audit: AuditService) {}
  private async crop(id: string) { const crop = await this.repo.crop(id); if (!crop) throw new MarketDomainError("Crop not found.", "CROP_NOT_FOUND", 404); return crop; }
  private analytics(history: Awaited<ReturnType<MarketIntelligenceRepository["history"]>>) {
    const values = history.map(x => x.modalPrice), latest = history.at(-1) ?? null;
    const recent = history.filter(x => x.date >= daysAgo(7)).map(x => x.modalPrice);
    const previous = history.filter(x => x.date >= daysAgo(14) && x.date < daysAgo(7)).map(x => x.modalPrice);
    const ch7 = percentChange(average(recent), average(previous)); const vol = volatility(values);
    return { latest: latest?.modalPrice ?? null, average: average(values) === null ? null : round(average(values)!), median: median(values) === null ? null : round(median(values)!), minimum: values.length ? Math.min(...values) : null, maximum: values.length ? Math.max(...values) : null, change7d: ch7, trend: trend(ch7), volatility: vol, freshness: latest ? freshness(latest.date) : null, recordsUsed: history.length };
  }
  async snapshot(cropId: string, filters: { mandiId?: string; state?: string; district?: string }) {
    const crop = await this.crop(cropId); const markets = filters.mandiId ? (await this.repo.mandi(filters.mandiId) ? await this.repo.latestMarkets(cropId, {}) : []) : await this.repo.latestMarkets(cropId, filters);
    const selected = filters.mandiId ? markets.filter(m => m.mandi.id === filters.mandiId) : markets;
    if (!selected.length) throw new MarketDomainError("Price data is unavailable.", "INSUFFICIENT_MARKET_DATA");
    const vals = selected.map(x => x.latest.modalPrice), last = selected.reduce((a,b) => a.latest.date > b.latest.date ? a : b).latest.date;
    const history = await this.repo.history(cropId, daysAgo(14), new Date(), filters.mandiId); const a = this.analytics(history);
    trackEvent("market_snapshot_viewed", { cropId, mandiId: filters.mandiId ?? null });
    return { crop, market: { totalMandisReporting: selected.length }, price: { unit: "INR_PER_QUINTAL", nationalAverage: round(average(vals)!), minimum: Math.min(...selected.map(x => x.latest.minPrice)), maximum: Math.max(...selected.map(x => x.latest.maxPrice)) }, trend: { direction: a.trend, changePercentage: a.change7d, period: "7D" }, dataQuality: { lastUpdated: last.toISOString(), recordsUsed: history.length, freshness: freshness(last) } };
  }
  async trends(cropId: string, input: { mandiId?: string; startDate: Date; endDate: Date }) { const crop = await this.crop(cropId); if (input.mandiId && !await this.repo.mandi(input.mandiId)) throw new MarketDomainError("Mandi not found.", "MANDI_NOT_FOUND", 404); const series = await this.repo.history(cropId, input.startDate, input.endDate, input.mandiId); if (!series.length) throw new MarketDomainError("Insufficient market data.", "INSUFFICIENT_MARKET_DATA"); const a = this.analytics(series); trackEvent("market_trend_viewed", { cropId, days: Math.ceil((input.endDate.getTime()-input.startDate.getTime())/86400000) }); return { crop, mandiId: input.mandiId ?? null, period: `${Math.ceil((input.endDate.getTime()-input.startDate.getTime())/86400000)}D`, series: series.map(x => ({ date: x.date.toISOString().slice(0,10), modalPrice: x.modalPrice, minPrice: x.minPrice, maxPrice: x.maxPrice })), summary: a };
  }
  private async candidates(cropId: string, location: { latitude: number; longitude: number }, radiusKm: number, filters: { state?: string; district?: string } = {}) {
    if (Math.abs(location.latitude) > 90 || Math.abs(location.longitude) > 180) throw new MarketDomainError("Invalid latitude or longitude.", "INVALID_LOCATION"); if (radiusKm <= 0 || radiusKm > MARKET_CONFIG.maxRadiusKm) throw new MarketDomainError("Radius must be between 0 and 500 km.", "INVALID_LOCATION");
    const degree = radiusKm / 111; const markets = await this.repo.latestMarkets(cropId, filters);
    const result: MarketCandidate[] = [];
    for (const m of markets) { if (m.mandi.latitude === null || m.mandi.longitude === null || Math.abs(m.mandi.latitude-location.latitude) > degree || Math.abs(m.mandi.longitude-location.longitude) > degree) continue; const distanceKm = haversineKm(location.latitude, location.longitude, m.mandi.latitude, m.mandi.longitude); if (distanceKm <= radiusKm) { const history = await this.repo.history(cropId, daysAgo(30), new Date(), m.mandi.id); result.push({ ...m, history, distanceKm }); } }
    if (!result.length) throw new MarketDomainError("No nearby markets found.", "NO_NEARBY_MARKETS_FOUND", 404); return result;
  }
  async nearby(cropId: string, location: { latitude: number; longitude: number }, radiusKm: number) { const crop = await this.crop(cropId); const markets = await this.candidates(cropId, location, radiusKm); trackEvent("nearby_market_search", { cropId, radiusKm }); return { crop, markets: markets.map(x => ({ mandi: x.mandi, distanceKm: x.distanceKm, modalPrice: x.latest.modalPrice, lastUpdated: x.latest.date.toISOString(), freshness: freshness(x.latest.date) })) }; }
  async compare(cropId: string, input: { state?: string; district?: string; location?: { latitude: number; longitude: number }; radiusKm?: number }) { const crop = await this.crop(cropId); const markets = input.location ? await this.candidates(cropId, input.location, input.radiusKm ?? 150, input) : (await this.repo.latestMarkets(cropId, input)).map(x => ({ ...x, history: [] })); if (!markets.length) throw new MarketDomainError("Price data is unavailable.", "INSUFFICIENT_MARKET_DATA"); const regionalAverage = average(markets.map(x => x.latest.modalPrice))!; trackEvent("markets_compared", { cropId }); return { crop, regionalAverage: round(regionalAverage), data: markets.map(x => { const a = this.analytics(x.history); return { mandi: x.mandi, price: { modalPrice: x.latest.modalPrice, unit: "INR_PER_QUINTAL" }, distanceKm: x.distanceKm ?? null, trend: a.trend, change7d: a.change7d, regionalDifferencePercentage: percentChange(x.latest.modalPrice, regionalAverage) }; }) };
  }
  async recommend(cropId: string, location: { latitude: number; longitude: number }, radiusKm: number, quantity?: number, actor?: AuthenticatedUserContext) { const crop = await this.crop(cropId); const candidates = await this.candidates(cropId, location, radiusKm); const regionalAverage = average(candidates.map(c => c.latest.modalPrice))!; const maxPrice = Math.max(...candidates.map(c => c.latest.modalPrice)); const scored = candidates.map(c => { const a = this.analytics(c.history); const factors: Record<string, number> = { price: c.latest.modalPrice / maxPrice, distance: 1 - (c.distanceKm ?? radiusKm) / radiusKm, trend: a.change7d === null ? 0.5 : Math.max(0, Math.min(1, (a.change7d + 10) / 20)), stability: a.volatility.score === null ? 0.5 : Math.max(0, 1 - a.volatility.score), freshness: a.freshness === "FRESH" ? 1 : a.freshness === "RECENT" ? .7 : a.freshness === "STALE" ? .4 : .1 }; const weights: Record<string,number> = { price:.35, distance:.2, trend:.2, stability:.15, freshness:.1 }; const score = round(Object.entries(weights).reduce((s,[k,w]) => s + factors[k]*w, 0)*100); const reasons = [c.latest.modalPrice > regionalAverage ? `Price is ${round(((c.latest.modalPrice/regionalAverage)-1)*100)}% above the nearby-market average` : "Price is competitive with nearby markets", a.trend === "UP" || a.trend === "STRONGLY_UP" ? "Market prices show an upward trend" : "Recent market trend is stable", `Market is within ${c.distanceKm} km`, a.volatility.level === "LOW" ? "Recent prices are relatively stable" : "Use current prices as an indicator, not a guarantee"]; return { rank: 0, mandi: c.mandi, price: c.latest.modalPrice, distanceKm: c.distanceKm, estimatedGrossRevenue: quantity ? round(quantity*c.latest.modalPrice) : null, estimatedTransportCost: null, estimatedNetRealization: null, trend: a.trend, volatility: a.volatility.level, score, reasons, factorsUsed: Object.keys(factors), omittedFactors: ["arrivals", "transportCost", "marketCharges"], recommendationConfidence: confidence(a.recordsUsed, a.freshness ?? "OUTDATED", a.volatility.score) }; }).sort((a,b) => b.score-a.score).map((x,i) => ({...x, rank:i+1}));
    if (actor) await this.audit.record({ actorUserId: actor.id, action: "MARKET_RECOMMENDATION_GENERATED", entityType: "MarketRecommendation", entityId: cropId, metadata: { radiusKm, count: scored.length } }); trackEvent("market_recommendation_generated", { cropId, radiusKm }); return { crop, location: { latitude: location.latitude, longitude: location.longitude }, recommendations: scored, disclaimer: "Recommendations are based on available market data and do not guarantee future prices or sale outcomes." };
  }
  async mandiOverview(mandiId: string) { const mandi = await this.repo.mandi(mandiId); if (!mandi) throw new MarketDomainError("Mandi not found.", "MANDI_NOT_FOUND", 404); const activity = await this.repo.overview(mandiId); const last = activity.reduce<Date | null>((d,x) => !d || (x._max.observedDate && x._max.observedDate > d) ? x._max.observedDate : d, null); return { mandi, recentActivity: { cropsAvailable: activity.length, lastUpdated: last?.toISOString() ?? null }, marketHealth: { dataFreshness: last ? freshness(last) : null } }; }
  async lotRecommendation(user: AuthenticatedUserContext, publicId: string, radiusKm: number) { const lot = await this.lots.findByPublicId(publicId); if (!lot) throw new NotFoundError("Lot not found."); const farmerId = user.role === "FARMER" ? (await this.farmers.ensure(user.id)).id : null; if (!await this.lotAuth.canAccessLot(user, lot, farmerId)) throw new NotFoundError("Lot not found."); const location = lot.farm?.latitude != null && lot.farm?.longitude != null ? { latitude: lot.farm.latitude, longitude: lot.farm.longitude } : null; if (!location) throw new MarketDomainError("A farm location is required for lot recommendations.", "LOCATION_REQUIRED"); return this.recommend(lot.cropId, location, radiusKm, Number(lot.availableQuantityKg) / 100, user); }
}
