"use client";
import * as React from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Truck, Search } from "lucide-react";
import { RoleProtectedPage } from "@/components/RoleProtectedPage";
import { PageHeader } from "@/components/ui/stat-card";
import { Card, Alert } from "@/components/ui/primitives";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Button } from "@/components/ui/button";
import { transporterApi, transporterAdminApi } from "@/services/transporterApi";

function Content(){const [state,setState]=React.useState(""); const [verified,setVerified]=React.useState(""); const [search,setSearch]=React.useState(""); const qc=useQueryClient(); const list=useQuery({queryKey:["admin","transporters",state,verified],queryFn:()=>transporterApi.discover({state:state||undefined as any,verified:verified||undefined as any}),retry:false}); const verify=useMutation({mutationFn:({id,status}:{id:string;status:string})=>transporterAdminApi.verifyTransporter(id,status),onSuccess:()=>qc.invalidateQueries({queryKey:["admin","transporters"]})}); const items=Array.isArray(list.data)?list.data:(list.data?.transporters??list.data?.items??[]); const filtered=items.filter((x:any)=>!search||JSON.stringify(x).toLowerCase().includes(search.toLowerCase())); return <div><PageHeader title="Transport Network" description="Discover registered transporters and apply the backend verification workflow."/><Card className="mb-6"><div className="grid gap-3 sm:grid-cols-3"><div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search"/></div><Input value={state} onChange={e=>setState(e.target.value)} placeholder="State filter"/><Select value={verified} onChange={e=>setVerified(e.target.value)}><option value="">Any verification</option><option value="true">Verified</option><option value="false">Unverified</option></Select></div></Card>{list.isError?<Alert variant="info">No transporter records could be loaded with these filters.</Alert>:<div className="space-y-3">{filtered.map((t:any)=><Card key={t.publicId??t.id}><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-start gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-accent/20"><Truck className="h-5 w-5"/></span><div><h2 className="font-semibold">{t.businessName??t.legalName??t.contactName??"Transporter"}</h2><p className="text-sm text-muted-foreground">{t.verificationStatus??"PENDING"} · {t.providerType??"Provider"}</p></div></div><div className="flex gap-2"><Button className="w-auto px-3" disabled={verify.isPending} onClick={()=>verify.mutate({id:t.publicId,status:"VERIFIED"})}>Verify</Button><Button variant="destructive" className="w-auto px-3" disabled={verify.isPending} onClick={()=>verify.mutate({id:t.publicId,status:"REJECTED"})}>Reject</Button></div></div></Card>)}{filtered.length===0&&<Card><p className="text-sm text-muted-foreground">No transporters match the current filters.</p></Card>}</div>}</div>}
export default function AdminTransportersPage(){return <RoleProtectedPage role="ADMIN"><Content/></RoleProtectedPage>}
